### ISSUE TITLE
Multiple samples/vcf files

### ISSUE THREAD

**Issue by FriederikeHanssen** [cccnrc/plot-VCF#2]
IS it possible to plot multiple samples either all in one vcf file or load multiple vcf files at once?

**Comment by cccnrc** [comment]
Hi @FriederikeHanssen, thanks for reaching out! `plotVCF` is designed to handle and plot multiple sample in the same VCF file. As example, you can sub-select which samples you want to plot with [SAMPLE](https://github.com/cccnrc/plot-VCF#sample-focused-plot), differentiate each sample variants with [SHAPE](https://github.com/cccnrc/plot-VCF#sample-focused-plot---differentiate), group samples with [COLOR_SAMPLE](https://github.com/cccnrc/plot-VCF#sample-focused-plot---color-groups), and [much more](https://github.com/cccnrc/plot-VCF)!

It is not currently possible to load multiple VCF files into `plotVCF` (if you are interested in helping develop this option we are more than happy to help you out :wink:), but you can always merge your different VCF files first (take a look at [vcftools merge-vcf](https://cyverse.atlassian.net/wiki/spaces/DEapps/pages/259063974/vcftools-merge+0.1.16#:~:text=vcftools%2Dmerge%20merges%20two%20or,concatenating%20VCFs%20split%20by%20chromosome.) or [bcftools merge](https://samtools.github.io/bcftools/bcftools.html#merge)) and then pass the VCF file to `plotVCF`

I hope it was helpful, do not hesitate to further comment in case you need additional help
