### ISSUE TITLE
createVCFplot() position plot - VAR_COL error

### ISSUE THREAD

**Issue by cccnrc** [cccnrc/plot-VCF#4]
Originally posted by @mkyriak:

I run the command to create the plot as follows: <br> 
`> createVCFplot(chr1, FASTA_FILE = assembly, CHR_NAMES = "1")`
However, I am getting the following error and I don't understand which field is the "VAR_COL": <br>
```
---------------------------------------------------------------------------
------------------------>   plotVCF v0.0.0.9000   <------------------------
---------------------------------------------------------------------------
    -> input VCF file: 	 ./merged-TP-samples-chr1.vcf.gz 
    -> input assembly: 	 hg38 
    -> input chromos: 	 1 
    -> input VAR_FLAG: 	 POS 
    -> input SAMPLE: 	 ALL 
    -> input FASTA: 	 ~/Documents/Analysis/ref/b37/renamed_human_g1k_v37.fasta 
    -> COLOR_SAMPLE: 	 1 groups specified
---------------------------------------------------------------------------

 -> loading FASTA file ...

 -> loading VCF file ...
  -> passed VCF file extension: gz 
  -> indexing VCF file ...
  -> reading VCF file ...
    -> VCF samples: 63 
Error in cbind(POS_COL, rownames(GENO_COL), VAR_COL, GENO_COL) : 
  object 'VAR_COL' not found
```
I appreciate your help.

_Originally posted by @mkyriak in https://github.com/cccnrc/plot-VCF/issues/1#issuecomment-1335812498_

**Comment by cccnrc** [comment]
Thanks so much @mkyriak for sharing this! I think it was related to a problem in default `VAR_FLAG` that should be fixed now. Can you try to update to latest version and re-run this? Let me know if you have any problem

**Comment by cccnrc** [comment]
Hi @mkyriak, I am gonna close this issue in 3 days from now if I do not receive any further communication from you. 
Hope it worked. Let me know :wink:

**Comment by mkyriak** [comment]
My apologies for the super late reply, I somehow missed this. I tried it lately now and it worked perfectly.
Thank you for your prompt response! :)
